### Task 1

In [4]:
import pandas as pd
import numpy as np

In [5]:
data = pd.read_csv('vgsalesGlobale.csv')

In [6]:
# * Calculate the total global sales for all games in the dataset.
total_sales = data['Global_Sales'].sum()
print(total_sales)

8920.44


In [40]:
# * Find the game with the highest global sales.
highest_sales = data['Global_Sales'].max()

# Printing the name of the game with the highest global sales
print(highest_sales)

82.74


In [8]:
# Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
average_sales = data[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].mean()
print(average_sales)

NA_Sales       0.264667
EU_Sales       0.146652
JP_Sales       0.077782
Other_Sales    0.048063
dtype: float64


In [10]:
# Find the top 5 most popular game genres based on global sales.
top_5_genres = data.groupby('Genre')['Global_Sales'].sum().sort_values(ascending=False).head(5)
print(top_5_genres)

Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64


In [12]:
# Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
total_sales_per_genre = data.groupby('Genre')[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].sum()
most_popular_genre = total_sales_per_genre['NA_Sales'].idxmax()
print(most_popular_genre)

Action


In [13]:
# Print the last 10 rows.
data.tail(10)

Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
16589  2016.0        Action        dramatic create      0.00      0.00   
16590  2007.0  Role-Playing     Falcom Corporation      0.00      0.00   
16591  2004.0     Adventure                Ubisoft      0.01      0.00   
16592  2008.0    Simulation              Destineer      0.01      0.00   
16593  2002.0      Platform                  Kemco      0.01      0.00   
16594  2003.0       Shooter             Infogrames      0.01      0.00   
16595  2008.0        Racing             Activision      0.00      0.00   
16596  2010.0        Puzzle               7G//AMES      0.00      0.01   
16597  2003.0      Platform                Wanadoo      0.01      0.00   

       JP_Sales  Other_Sales  Global_Sales  
16588      0.00          0.0          0.01  
16589      0.01          0.0          0.01  
16590      0.01          0.0          0.01  
16591      0.00          0.0          0.01  
16592      0.00          0.0          0.01  
16593      0.00          0.0          0.01  
16594      0.00          0.0          0.01  
16595      0.00          0.0          0.01  
16596      0.00          0.0          0.01  
16597      0.00          0.0          0.01

In [14]:
# Determine the top 3 gaming platforms with the highest global sales.
top_3_platforms = data.groupby('Platform')['Global_Sales'].sum().sort_values(ascending=False).head(3)
print(top_3_platforms)

Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64


In [15]:
#  Calculate the market share (percentage of global sales) for each genre.
market_share = data.groupby('Genre')['Global_Sales'].sum() / total_sales * 100
print(market_share)

Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64


In [16]:
# * Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)
correlation = data['NA_Sales'].corr(data['EU_Sales'])
print(correlation)

0.767726748370264


### Task 2

In [22]:
# English to Spanish
english_spanish = {
    'hello': 'hola',
    'goodbye': 'adiós',
    'thank you': 'gracias',
    'please': 'por favor',
    'good morning': 'buenos días',
    'good night': 'buenas noches',
    'yes': 'sí',
    'no': 'no',
    'water': 'agua',
    'food': 'comida'
}

# Ask user for input
while True:
    word = input('Enter a word: ').lower()
    if word == 'exit':
        break
    if word in english_spanish:
        print(f'The Spanish translation is: {english_spanish[word]}')
    else:
        print('Word not found in dictionary.')

Word not found in dictionary.
Word not found in dictionary.
Word not found in dictionary.
The Spanish translation is: buenos días
Word not found in dictionary.


### Task 3

In [27]:
# Function to classify emails into multiple types
def classify_emails(emails):
    important_keywords = {"meeting", "urgent", "project", "deadline", "client"}
    promotion_keywords = {"sale", "discount", "offer", "deal", "coupon"}
    spam_keywords = {"lottery", "win", "prize", "free money", "click here"}
    
    important = []
    promotions = []
    spam = []
    
    # Convert emails to lowercase for case-insensitive matching and then classify them
    for email in emails:
        email_lower = email.lower()
        
        if any(keyword in email_lower for keyword in important_keywords):
            important.append(email)
        elif any(keyword in email_lower for keyword in promotion_keywords):
            promotions.append(email)
        elif any(keyword in email_lower for keyword in spam_keywords):
            spam.append(email)
        else:
            important.append(email)
    
    return important, promotions, spam

# Sample emails
sample_emails = [
    "Urgent: Meeting scheduled for tomorrow",
    "Huge Discount on all products! Limited time offer",
    "You have won a lottery! Click here to claim",
    "Project deadline extended to next week",
    "Claim your free money now! Limited slots available"
]

# Classify sample emails
important_emails, promotional_emails, spam_emails = classify_emails(sample_emails)

# Print the results
print("Important Emails:", important_emails)
print("Promotional Emails:", promotional_emails)
print("Spam Emails:", spam_emails)


Important Emails: ['Urgent: Meeting scheduled for tomorrow', 'Project deadline extended to next week']
Promotional Emails: ['Huge Discount on all products! Limited time offer']
Spam Emails: ['You have won a lottery! Click here to claim', 'Claim your free money now! Limited slots available']


### Task 4

In [45]:
# Store Simulation
def online_store_shopping_cart():
    products = {
        1: "Laptop",
        2: "Headphones",
        3: "Smartphone",
        4: "Tablet",
        5: "Charger",
        6: "Backpack",
        7: "Mouse",
        8: "Keyboard",
        9: "Monitor",
        10: "External Hard Drive"
    }
    
    shopping_cart = []
    
    print("Welcome to the Online Store!")
    print("Available products:")
    for key, value in products.items():
        print(f"{key}: {value}")
    print("Enter 'q' to quit and proceed to checkout.")
    
    while True:
        choice = input("Enter the number of the product to add to cart: ")
        
        if choice.lower() == 'q':
            break
        
        if choice.isdigit():
            choice = int(choice)
            if choice in products:
                shopping_cart.append(products[choice])
                print(f"'{products[choice]}' added to cart.")
            else:
                print("Invalid choice. Please select a valid product number.")
        else:
            print("Invalid input. Please enter a number or 'q' to quit.")
    
    print("\nYour Shopping Cart:")
    if shopping_cart:
        for item in shopping_cart:
            print(f"- {item}")
    else:
        print("Your cart is empty.")
    
    print("Thank you for shopping with us!")

# Run the shopping cart function
online_store_shopping_cart()

Welcome to the Online Store!
Available products:
1: Laptop
2: Headphones
3: Smartphone
4: Tablet
5: Charger
6: Backpack
7: Mouse
8: Keyboard
9: Monitor
10: External Hard Drive
Enter 'q' to quit and proceed to checkout.
'Headphones' added to cart.
'Smartphone' added to cart.
'Laptop' added to cart.
'Headphones' added to cart.
Invalid choice. Please select a valid product number.
'Charger' added to cart.
'Headphones' added to cart.
Invalid choice. Please select a valid product number.

Your Shopping Cart:
- Headphones
- Smartphone
- Laptop
- Headphones
- Charger
- Headphones
Thank you for shopping with us!


### Task 5

In [49]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

# Element-wise addition
result = arr1 + arr2
print(result)

# Element-wise product
product = arr1 * arr2
print(product)

[ 7  9 11 13 15]
[ 6 14 24 36 50]


### Task 6

In [53]:
# Create a 1D array
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13])

# Reshape the 1D array into a 2D array with dimensions (3, 4)
arr2d = arr1.reshape(3, 4)

# Create two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Concatenate the arrays horizontally
horizontal = np.hstack((arr1, arr2))

# Concatenate the arrays vertically
vertical = np.vstack((arr1, arr2))

# Print the arrays
print(arr2d)
print(horizontal)
print(vertical)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 12 13]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


### Task 7

In [59]:
list1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
list1 = list1[::-1]
print(list1)

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
